[package]
name = "ews"
version = "0.1.0"
authors = ["Dave Yarwood <dave.yarwood@gmail.com>"]

[dependencies]
clap                = "2.10.0"
schemamama_rusqlite = "0.5.0"
schemamama          = "0.2.0"
rusqlite            = "0.6.0"
time                = "0.1.35"
